name: ekayanaarama
description: EkayanaArama
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+10

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_svg: ^1.1.0
  cached_network_image: ^3.2.3
  smooth_page_indicator: ^1.1.0
  flutter_html: ^3.0.0-alpha.5
  number_paginator: ^0.2.3
  screenshot: ^1.3.0
  share_plus: ^4.1.0
  path_provider: ^2.0.11
  image_gallery_saver: ^1.7.1
  get: ^4.6.5
  flutter_cached_pdfview: ^0.4.1
  flutter_native_splash: ^2.2.0
  intl: ^0.18.1
  permission_handler: ^10.2.0
  flutter_local_notifications: ^14.1.1
  flutter_timezone: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - asset/icon/
    - asset/json/
    - asset/json/daily_reflection/
    - asset/drawable/

  fonts:
    - family: Inter
      fonts:
        - asset: asset/fonts/Inter-Regular.ttf
