// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApGZlTrLDcZ__mkPvJQHUoW3EDzKxIh8Y',
    appId: '1:515390596473:android:d387f908e730a992',
    messagingSenderId: '515390596473',
    projectId: 'ekayana-6b906',
    databaseURL: 'https://ekayana-6b906.firebaseio.com',
    storageBucket: 'ekayana-6b906.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2BHPetPqblC6u5-AvqgykI2bgZiBKZTI',
    appId: '1:515390596473:ios:96e10853f64300f1fffba8',
    messagingSenderId: '515390596473',
    projectId: 'ekayana-6b906',
    databaseURL: 'https://ekayana-6b906.firebaseio.com',
    storageBucket: 'ekayana-6b906.appspot.com',
    iosClientId: '515390596473-geo9b58gcgicac3sa4eut77jeof79s47.apps.googleusercontent.com',
    iosBundleId: 'id.or.ekayana.ekayanaarama',
  );
}